# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: auth_postgres
    environment:
      POSTGRES_DB: authentication_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    build:
      context: /home/salome/tallerApis/app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

volumes:
  postgres_data:
